spring:
  application:
    name: tgBotService
  main:
    allow-bean-definition-overriding: true

server:
  port: 8082

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

bot:
  name: "XyL1GaN4eG_weatherBot"
  token: ${TG_BOT_API_KEY}

translate_script:
  api: ${GOOGLE_SCRIPT_TRANSLATE_KEY}