spring:
  application:
    name: tgBotService
  main:
    allow-bean-definition-overriding: true

server:
  port: 8082

rabbitmq:
  host:     ${RABBITMQ_HOST}
  port:     ${RABBITMQ_PORT}
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}

bot:
  name: "XyL1GaN4eG_weatherBot"
  token: ${TG_BOT_API_KEY}

user-service:
  base-url: ${USER_SERVICE_BASE_URL}

weather-service:
  base-url: ${WEATHER_SERVICE_BASE_URL}