#TODO: remove hardcoding
spring:
  application:
    name: tgBotService

server:
  port: 8082

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

bot:
  name: "XyL1GaN4eG_weatherBot"
#  TODO: remove hardcoding
  token: "7322702173:AAHYHycNmHgeVULZEh5KWCtAHaBxqApUDS8"