spring:
  application:
    name: userService
  datasource:
    url: jdbc:postgresql://localhost:5432/weatherproject
    username: username
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest