#TODO: remove hardcoding
spring:
  application:
    name: weatherApiService
  datasource:
    url: jdbc:postgresql://localhost:5432/weatherproject
    username: username
    password: password
    hikari:
      allow-pool-suspension: true  # Enable Hikari pool suspension for JVM checkpoint restore
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          allow_jdbc_metadata_access: false  # Disable Hibernate usage of JDBC metadata
    show-sql: true  # Enable logging of SQL statements
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Specify the dialect for PostgreSQL
  sql:
    init:
      mode: never  # Disable database initialization performed by Spring
server:
  port: 8081

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest


weather:
  api:
    url: "http://api.weatherapi.com/v1/current.json?key=b754ca0088e64db9afe102203240306&q={city}&aqi=no"
#      "http://api.weatherapi.com/v1/current.json?key=${WEATHER_API_KEY}&q={city}&aqi=yes"
