spring:
  application:
    name: weatherApiService
  datasource:
    url:      ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      allow-pool-suspension: true  # Enable Hikari pool suspension for JVM checkpoint restore
  jpa:
    hibernate:
      #      ddl-auto: none  # Disable automatic schema generation by Hibernate
      properties:
        hibernate:
          allow_jdbc_metadata_access: false  # Disable Hibernate usage of JDBC metadata
    show-sql: true  # Enable logging of SQL statements
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Specify the dialect for PostgreSQL
  sql:
    init:
      mode: never  # Disable database initialization performed by Spring
server:
  port: 8081

rabbitmq:
  host:     ${RABBITMQ_HOST}
  port:     ${RABBITMQ_PORT}
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}

weather:
  api:
    url:
      "http://api.weatherapi.com/v1/current.json?key=${WEATHER_API_KEY}&q={city}&aqi=no"
