spring:
  application:
    name: weatherApiService
  datasource:
    url: jdbc:postgresql://localhost:5432/weatherproject
    username: username
    password: password
    hikari:
      allow-pool-suspension: true  # Включить приостановку пула Hikari для восстановления контрольной точки JVM
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect  # Указание диалекта для PostgreSQL
    hibernate:
      ddl-auto: none  # Отключить автоматическую генерацию схемы Hibernate
      properties:
        hibernate:
          allow_jdbc_metadata_access: false  # Отключить использование JDBC метаданных Hibernate
    show-sql: true  # Включить логирование SQL-запросов
  sql:
    init:
      mode: never  # Отключить инициализацию базы данных, выполняемую Spring

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

weather:
  api:
    url: "http://api.weatherapi.com/v1/current.json?key=${WEATHER_API_KEY}&q={city}&aqi=yes"
