name: Cleanup server

on:
  workflow_call:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and clean up source code
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Cleaning up source code..."
            sudo rm -rf /home/xyl1gan4eg/myJavaProjects/weatherProject/src/  # Удалить исходный код с сервера
            echo "Cleanup completed."
