name: Cleanup server

on:
  workflow_call:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and clean up source code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.CLIENT_PRIVATE_KEY }}
          script: |
            echo "Cleaning up source code..."
            sudo rm -Rf /home/xyl1gan4eg/myJavaProjects/weatherProject/  # Удалить исходный код с сервера
            echo "Cleanup completed."