name: Deploy User Service

on:
  workflow_call:

jobs:
  deploy_user_service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy userService source code via ssh
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.CLIENT_PRIVATE_KEY }}
          source: userService/
          target: /home/xyl1gan4eg/myJavaProjects/weatherProject/

      - name: SSH into server and build userService
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.CLIENT_PRIVATE_KEY }}
          script: |
            echo "Building userService on server..."
            cd /home/xyl1gan4eg/myJavaProjects/weatherProject/userService
            mvn clean install -DskipTests
            echo "Build completed."

      - name: Restart userService
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.CLIENT_PRIVATE_KEY }}
          script: |
            sudo systemctl stop user-service.service
            sudo cp /home/xyl1gan4eg/myJavaProjects/weatherProject/userService/*.jar /opt/userService/
            sudo systemctl start user-service.service
