name: Deploy Telegram weather bot Service

on:
  workflow_call:

jobs:
  deploy_tg_bot_service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy tgBotService source code via ssh
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.CLIENT_PRIVATE_KEY }}
          source: tgBotService/
          target: /home/xyl1gan4eg/myJavaProjects/weatherProject/

      - name: SSH into server and build tgBotService
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.CLIENT_PRIVATE_KEY }}
          script: |
            echo "Building tgBotService on server..."
            cd /home/xyl1gan4eg/myJavaProjects/weatherProject/tgBotService
            mvn clean install -DskipTests
            echo "Build completed."

      - name: Set environment variables and restart tgBotService
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.CLIENT_PRIVATE_KEY }}
          script: |
            echo "Setting environment variables..."
            echo "export RABBITMQ_HOST=${{ secrets.RABBITMQ_HOST }}" | sudo tee -a /etc/environment
            echo "export RABBITMQ_PORT=${{ secrets.RABBITMQ_PORT }}" | sudo tee -a /etc/environment
            echo "export RABBITMQ_USERNAME=${{ secrets.RABBITMQ_USERNAME }}" | sudo tee -a /etc/environment
            echo "export RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_PASSWORD }}" | sudo tee -a /etc/environment
            echo "export TG_BOT_API_KEY=${{ secrets.TG_BOT_API_KEY }}" | sudo tee -a /etc/environment
            echo "export USER_SERVICE_BASE_URL=${{ secrets.USER_SERVICE_BASE_URL }}" | sudo tee -a /etc/environment
            echo "export WEATHER_SERVICE_BASE_URL=${{ secrets.WEATHER_SERVICE_BASE_URL }}" | sudo tee -a /etc/environment
            source /etc/environment
            echo "Environment variables set."

            echo "Restarting tgBotService..."
            sudo systemctl stop tg-bot-service.service
            sudo cp /home/xyl1gan4eg/myJavaProjects/weatherProject/tgBotService/*.jar /opt/tgBotService/
            sudo systemctl start tg-bot-service.service
            echo "tgBotService restarted."
