name: Deploy Weather Service

on:
  workflow_call:

jobs:
  deploy_weather_service:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy source code weatherService to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'weatherService/src/'
          target: '/home/xyl1gan4eg/myJavaProjects/weatherProject/weatherService/src/'
          port: 22
          timeout: 30s
          command_timeout: 10m
          use_insecure_cipher: false
          rm: false
          debug: true
          strip_components: 0
          overwrite: true
          tar_dereference: false
          tar_exec: tar

      - name: SSH into server and build weatherService
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Building weatherService on server..."
            cd /home/xyl1gan4eg/myJavaProjects/weatherProject/weatherService/src/
            mvn -B package
            echo "Build completed."

      - name: Deploy weatherService JAR to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: '/home/xyl1gan4eg/myJavaProjects/weatherProject/weatherService/target/weatherService-0.0.1-SNAPSHOT.jar'
          target: '/opt/weatherService/'
          port: 22
          timeout: 30s
          command_timeout: 10m
          use_insecure_cipher: false
          rm: false
          debug: true
          strip_components: 0
          overwrite: true
          tar_dereference: false
          tar_exec: tar

      - name: SSH into server and restart weatherService
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Restarting weatherService..."
            sudo systemctl stop weather-service || true
            sudo cp /opt/weatherService/weatherService-0.0.1-SNAPSHOT.jar /opt/weatherService/
            sudo systemctl start weather-service
