name: Deploy Weather Api Service

on:
  workflow_call:

jobs:
  deploy_weather_api_service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy weatherApiService source code via ssh
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.CLIENT_PRIVATE_KEY }}
          source: weatherApiService/
          target: /home/xyl1gan4eg/myJavaProjects/weatherProject/

      - name: SSH into server and build weatherApiService
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.CLIENT_PRIVATE_KEY }}
          script: |
            echo "Building weatherApiService on server..."
            cd /home/xyl1gan4eg/myJavaProjects/weatherProject/weatherApiService
            mvn clean install -DskipTests
            echo "Build completed."
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

      - name: Set environment variables and restart weatherApiService
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.CLIENT_PRIVATE_KEY }}
          script: |
            sudo systemctl stop weather-api-service.service
            sudo cp /home/xyl1gan4eg/myJavaProjects/weatherProject/weatherApiService/*.jar /opt/weatherApiService/
            sudo systemctl start weather-api-service.service
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}