name: Deploy User Service

on:
  workflow_call:

jobs:
  deploy_tg_bot_service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy tgBotService source code via SSH
        uses: appleboy/scp-action@v0.0.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: './tgBotService/*'
          target: '/home/xyl1gan4eg/myJavaProjects/weatherProject/tgBotService/'

      - name: Build tgBotService on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Building tgBotService on server..."
            cd /home/xyl1gan4eg/myJavaProjects/weatherProject/tgBotService
            mvn -B package
            echo "Build completed."

      - name: Restart tgBotService on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Restarting tgBotService..."
            sudo systemctl stop tg-bot-service || true
            sudo cp /home/xyl1gan4eg/myJavaProjects/weatherProject/tgBotService/target/tgBotService-0.0.1-SNAPSHOT.jar /opt/tgBotService/
            sudo systemctl start tg-bot-service
            echo "tgBotService restarted."
