name: Deploy User Service

on:
  workflow_call:

jobs:
  deploy_tg_bot_service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files via SCP
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
        run: |
          scp -o StrictHostKeyChecking=no -r ./tgBotService/ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/home/xyl1gan4eg/myJavaProjects/weatherProject/


      - name: SSH into server and build tgBotService
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
        run: |
          ssh -vvv -o StrictHostKeyChecking=no ${SERVER_USERNAME}@${SERVER_HOST} 'bash -s' << 'EOF'
          echo "Building tgBotService on server..."
          cd /home/xyl1gan4eg/myJavaProjects/weatherProject/tgBotService
          mvn -B package
          echo "Build completed."
          EOF

      - name: SSH into server and restart tgBotService
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
        run: |
          ssh -vvv -o StrictHostKeyChecking=no ${SERVER_USERNAME}@${SERVER_HOST} 'bash -s' << 'EOF'
          echo "Restarting tgBotService..."
          sudo systemctl stop tg-bot-service || true
          sudo cp /opt/tgBotService/tgBotService-0.0.1-SNAPSHOT.jar /opt/userService/
          sudo systemctl start tg-bot-service
          EOF