name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy_user_service:
    uses: ./.github/workflows/deploy_user_service.yml
    secrets: inherit  # Наследовать секреты от основного workflow

  deploy_weather_service:
    uses: ./.github/workflows/deploy_weather_service.yml
    secrets: inherit  # Наследовать секреты от основного workflow

#  builds:
#    uses: ./.github/workflows/builds.yml
#    secrets: inherit

  cleanup:
    uses: ./.github/workflows/cleanup.yml
    secrets: inherit  # Наследовать секреты от основного workflow