name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  cleanup:
    uses: ./.github/workflows/cleanup.yml
    secrets: inherit  # Наследовать секреты от основного workflow

  deploy_user_service:
    needs: cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if user service has changed
        id: check_changes
        run: |
          git fetch origin main
          if git diff --name-only HEAD^ HEAD | grep 'userService'; then
            echo "User service has changed"
            echo "should_deploy=true" >> $GITHUB_ENV
          else
            echo "User service has not changed"
            echo "should_deploy=false" >> $GITHUB_ENV
          fi

      - name: Deploy user service
        if: env.should_deploy == 'true'
        uses: ./.github/workflows/deploy_user_service.yml
        secrets: inherit  # Наследовать секреты от основного workflow

  deploy_weather_service:
    needs: cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if weather service has changed
        id: check_changes
        run: |
          git fetch origin main
          if git diff --name-only HEAD^ HEAD | grep 'weatherApiService'; then
            echo "Weather service has changed"
            echo "should_deploy=true" >> $GITHUB_ENV
          else
            echo "Weather service has not changed"
            echo "should_deploy=false" >> $GITHUB_ENV
          fi

      - name: Deploy weather service
        if: env.should_deploy == 'true'
        uses: ./.github/workflows/deploy_weather_service.yml
        secrets: inherit  # Наследовать секреты от основного workflow

  deploy_tg_bot_service:
    needs: cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if tg bot service has changed
        id: check_changes
        run: |
          git fetch origin main
          if git diff --name-only HEAD^ HEAD | grep 'tgBotService'; then
            echo "TG Bot service has changed"
            echo "should_deploy=true" >> $GITHUB_ENV
          else
            echo "TG Bot service has not changed"
            echo "should_deploy=false" >> $GITHUB_ENV
          fi

      - name: Deploy tg bot service
        if: env.should_deploy == 'true'
        uses: ./.github/workflows/deploy_tg_bot_service.yml
        secrets: inherit  # Наследовать секреты от основного workflow
