name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  cleanup:
    uses: ./.github/workflows/cleanup.yml
    secrets: inherit  # Наследовать секреты от основного workflow

  deploy_user_service:
    needs: cleanup
    uses: ./.github/workflows/deploy_user_service.yml
    secrets: inherit  # Наследовать секреты от основного workflow

  deploy_weather_service:
    needs: cleanup
    uses: ./.github/workflows/deploy_weather_service.yml
    secrets: inherit  # Наследовать секреты от основного workflow

  deploy_tg_bot_service:
    needs: cleanup
    uses: ./.github/workflows/deploy_tg_bot_service.yml
    secrets: inherit  # Наследовать секреты от основного workflow
