name: Deploy Telegram weather bot Service

on:
  workflow_call:

jobs:
  deploy_tg_bot_service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy tgBotService source code via ssh
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.CLIENT_PRIVATE_KEY }}
          source: tgBotService/
          target: /home/xyl1gan4eg/myJavaProjects/weatherProject/

      - name: SSH into server and test tgBotService
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.CLIENT_PRIVATE_KEY }}
          script: |
            echo "Building tgBotService on server..."
            cd /home/xyl1gan4eg/myJavaProjects/weatherProject/tgBotService
            mvn test
            echo "test completed."

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}


      - name: SSH into server and build tgBotService
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.CLIENT_PRIVATE_KEY }}
          script: |
            echo "Building tgBotService on server..."
            cd /home/xyl1gan4eg/myJavaProjects/weatherProject/tgBotService
            mvn clean install
            echo "Build completed."


      - name: Restart tgBotService
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.CLIENT_PRIVATE_KEY }}
          script: |
            sudo systemctl stop tg-bot-service.service
            sudo cp /home/xyl1gan4eg/myJavaProjects/weatherProject/tgBotService/*.jar /opt/tgBotService/
            sudo systemctl start tg-bot-service.service