name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy_user_service:
    uses: ./.github/workflows/deploy_user_service.yml
    secrets: inherit  # Наследовать секреты от основного workflow

  deploy_weather_service:
    uses: ./.github/workflows/deploy_weather_service.yml
    secrets: inherit  # Наследовать секреты от основного workflow

  deploy_tg_bot_service:
    uses: ./.github/workflows/deploy_tg_bot_service.yml
    secrets: inherit  # Наследовать секреты от основного workflow
